In [2]:
!pip install sqlalchemy==1.3.2
%load_ext sql
%sql postgresql://dlstlr28:Dlstlr28!1@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/prod

Collecting sqlalchemy==1.3.2
  Downloading https://files.pythonhosted.org/packages/2a/9b/9b8aa2d5dbe2e4052cb4c84b8cf5e31686943f24b0565f436439bdc343b5/SQLAlchemy-1.3.2.tar.gz (5.9MB)
     |████████████████████████████████| 5.9MB 2.1MB/s
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py) ... done
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.3.2-cp37-cp37m-linux_x86_64.whl size=1182909 sha256=9732cc86fd6693b972541040c2482bc5e40c7dc879b14a90975f78cfcd567f72
  Stored in directory: /root/.cache/pip/wheels/36/2a/2e/c0c1dbccff6eb1d7f7e9fdd074839aa24f03c7dbda0dced17c
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
  Found existing installation: SQLAlchemy 1.4.15
    Uninstalling SQLAlchemy-1.4.15:
      Successfully uninstalled SQLAlchemy-1.4.15
Successfully installed sqlalchemy-1.3.2

/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

'Connected: dlstlr28@prod'

# Assignments 1: 따라해보기

복사 코드는 airflow를 통해 수행

In [ ]:
%%sql
SELECT *
FROM dlstlr28.name_gender

 * postgresql://dlstlr28:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/prod
99 rows affected.

[('Amryn', 'Unisex'),
 ('Apurva', 'Unisex'),
 ('Aryion', 'M'),
 ('Alixia', 'F'),
 ('Alyssarose', 'F'),
 ('Arvell', 'M'),
 ('Aibel', 'M'),
 ('Atiyyah', 'F'),
 ('Adlie', 'F'),
 ('Anyely', 'F'),
 ('Aamoni', 'F'),
 ('Ahman', 'M'),
 ('Arlane', 'F'),
 ('Armoney', 'F'),
 ('Atzhiry', 'F'),
 ('Antonette', 'F'),
 ('Akeelah', 'F'),
 ('Abdikadir', 'M'),
 ('Arinze', 'M'),
 ('Arshaun', 'M'),
 ('Alexandro', 'M'),
 ('Ayriauna', 'F'),
 ('Aqib', 'M'),
 ('Alleya', 'F'),
 ('Aavah', 'F'),
 ('Anesti', 'Unisex'),
 ('Adalaide', 'F'),
 ('Analena', 'F'),
 ('Alaeyah', 'F'),
 ('Albena', 'F'),
 ('Aimi', 'F'),
 ('Adwaith', 'M'),
 ('Arkady', 'M'),
 ('Astyn', 'Unisex'),
 ('Adelee', 'F'),
 ('Agata', 'F'),
 ('Alegna', 'F'),
 ('Altan', 'M'),
 ('Ahnaleigh', 'F'),
 ('Algie', 'Unisex'),
 ('Ashanti', 'F'),
 ('Aislyn', 'F'),
 ('Adaleine', 'F'),
 ('Anthnoy', 'M'),
 ('Algernon', 'M'),
 ('Aeryona', 'F'),
 ('Adrinne', 'F'),
 ('Addell', 'F'),
 ('Avril', 'F'),
 ('Ahni', 'F'),
 ('Aimon', 'M'),
 ('Adolpho', 'M'),
 ('Ahuva', 'F'),
 ('Aurielle', 'F'),
 ('Aveana', 'F'),
 ('Aliyia', 'F'),
 ('Alesander', 'M'),
 ('Adnrea', 'F'),
 ('Anjae', 'F'),
 ('Alvine', 'F'),
 ('Adorah', 'F'),
 ('Adlemi', 'F'),
 ('Alesi', 'F'),
 ('Alontae', 'M'),
 ('Antonny', 'M'),
 ('Adarah', 'F'),
 ('Ayreanna', 'F'),
 ('Antyon', 'M'),
 ('Andia', 'F'),
 ('Ashla', 'F'),
 ('Aspyn', 'F'),
 ('Antwanett', 'F'),
 ('Aundreia', 'F'),
 ('Audella', 'F'),
 ('Amari', 'Unisex'),
 ('Arsha', 'Unisex'),
 ('Aricella', 'F'),
 ('Adan', 'M'),
 ('Apasra', 'F'),
 ('Alaysha', 'F'),
 ('Anderson', 'M'),
 ('Aurelius', 'M'),
 ('Aerial', 'F'),
 ('Averleigh', 'F'),
 ('Aslean', 'F'),
 ('Arniesha', 'F'),
 ('Asyana', 'F'),
 ('Annjane', 'F'),
 ('Amabella', 'F'),
 ('Austinjohn', 'M'),
 ('Arloween', 'F'),
 ('Alula', 'M'),
 ('Anemone', 'F'),
 ('Amorina', 'F'),
 ('Anureet', 'F'),
 ('Arric', 'M'),
 ('Antonne', 'M'),
 ('Alyre', 'M'),
 ('Annaise', 'F')]

In [ ]:
%%sql

SELECT *
FROM dlstlr28.customer_features;
SELECT *
FROM dlstlr28.customer_variants;

 * postgresql://dlstlr28:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/prod
0 rows affected.
0 rows affected.

[]

# Assignments 2: Postgres 테이블을 더 추가해보기

In [ ]:
import psycopg2

# Redshift connection 함수
def get_Redshift_connection():
    host = "learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com"
    redshift_user = "dlstlr28"
    redshift_pass = "Dlstlr28!1"
    port = 5439
    dbname = "prod"
    conn = psycopg2.connect("dbname={dbname} user={user} host={host} password={password} port={port}".format(
        dbname=dbname,
        user=redshift_user,
        password=redshift_pass,
        host=host,
        port=port
    ))
    conn.set_session(autocommit=True)
    return conn.cursor()

/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

In [ ]:
%%sql

-- redshift 테이블 생성 테스트

CREATE TABLE dlstlr28.customer_features (
      customer_id int,
     engagement_level varchar(16),
     gender varchar(16),
     PRIMARY KEY (customer_id)
);
CREATE TABLE dlstlr28.customer_variants (
    customer_id int,
    variant varchar(8),
    primary key (customer_id)
);
CREATE TABLE dlstlr28.item_features (
    item_id int,
    quality float,
    popularity varchar(16),
    price int,
    primary key(item_id)
);
CREATE TABLE dlstlr28.customer_interactions (
    customer_id int,
    datestamp date,
    item_id int,
    clicked int,
    purchased int ,
    paidamount int,
    primary key(customer_id, datestamp, item_id)
);

 * postgresql://dlstlr28:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/prod
(psycopg2.ProgrammingError) Relation "customer_variants" already exists

[SQL: -- redshift 테이블 생성 테스트
CREATE TABLE dlstlr28.customer_variants (
    customer_id int,
    variant varchar(8),
    primary key (customer_id)
);]
(Background on this error at: http://sqlalche.me/e/f405)

In [ ]:
%%sql

SELECT *
FROM dlstlr28.customer_variants;
SELECT *
FROM dlstlr28.customer_features;
SELECT *
FROM dlstlr28.item_features;
SELECT *
FROM dlstlr28.customer_interactions;

# Assignments 3: Summary table을 빌드해보기

In [ ]:
from airflow import DAG
from airflow.operators import PythonOperator
from airflow.models import Variable
from airflow.hooks.postgres_hook import PostgresHook
from datetime import datetime
from datetime import timedelta
import requests
import logging
import psycopg2

def get_Redshift_connection():
    # Airflow web UI 에 등록된 Connection id
    hook = PostgresHook(postgres_conn_id='redshift_dev_db')
    return hook.get_conn().cursor()


def execSQL(**context):
    schema = context['params']['schema'] 
    table = context['params']['table']
    select_sql = context['params']['sql']

    cur = get_Redshift_connection()

    try:
        sql = "BEGIN;"
        sql += f"DROP TABLE IF EXISTS {schema}.{table};"
        sql += f"CREATE TABLE {schema}.{table} AS {select_sql};"
        sql += "END;"
        logging.info(sql)
        cur.execute(sql)
    except Exception as e:
        cur.execute("ROLLBACK;")
        logging.error("Failed to create summary table.")

dag = DAG(
        dag_id = "ctas_summary_table",
        start_date = datetime(2021, 5, 20),
        schedule_interval = '@once',
        catchup = False)

execsql = PythonOperator(
        task_id = 'execsql',
        python_callable = execSQL,
        params = {
            'schema' : 'analytics',
            'table': 'FirstLastChannel',
            'sql' : '''
                    SELECT DISTINCT A.userid,
                           FIRST_VALUE(A.channel) over(partition by A.userid order by B.ts rows between unbounded preceding and unbounded following) AS first_channel,
                           LAST_VALUE(A.channel) over(partition by A.userid order by B.ts rows between unbounded preceding and unbounded following) AS last_chaneel
                    FROM dlstlr28.user_session_channel AS A
                    LEFT JOIN dlstlr28.session_timestamp AS B
                    ON A.sessionid = B.sessionid;
                    '''
        },
        provide_context = True,  # 파라미터 전달을 위한 설정
        dag = dag
        )

execsql

In [7]:
%%sql
--월별 나이대의 총 구매량, 클릭 후 구매하지 않은 품목 수

SELECT datestamp, engagement_level,
       SUM(CASE WHEN purchased = 1 THEN price * paidamount ELSE 0 END) amount,
       COUNT(CASE WHEN (clicked = 1 and purchased = 0) THEN 1 END) AS clicked_only
FROM dlstlr28.customer_features AS cf
JOIN dlstlr28.customer_interactions AS ci ON cf.customer_id = ci.customer_id
JOIN dlstlr28.item_features AS itf ON ci.item_id = itf.item_id
GROUP BY 1, 2
ORDER BY 1, 2

 * postgresql://dlstlr28:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/prod
21 rows affected.

[(datetime.date(2019, 1, 11), '0-19', 665830, 5026),
 (datetime.date(2019, 1, 11), '20-49', 2271057, 17086),
 (datetime.date(2019, 1, 11), '50-up', 543074, 4075),
 (datetime.date(2019, 1, 12), '0-19', 764981, 5253),
 (datetime.date(2019, 1, 12), '20-49', 2407526, 17078),
 (datetime.date(2019, 1, 12), '50-up', 596373, 4254),
 (datetime.date(2019, 1, 13), '0-19', 712706, 5255),
 (datetime.date(2019, 1, 13), '20-49', 2229191, 16795),
 (datetime.date(2019, 1, 13), '50-up', 540585, 4259),
 (datetime.date(2019, 1, 14), '0-19', 719951, 5171),
 (datetime.date(2019, 1, 14), '20-49', 2275727, 16813),
 (datetime.date(2019, 1, 14), '50-up', 525135, 4085),
 (datetime.date(2019, 1, 15), '0-19', 708264, 5214),
 (datetime.date(2019, 1, 15), '20-49', 2312835, 17121),
 (datetime.date(2019, 1, 15), '50-up', 567223, 4175),
 (datetime.date(2019, 1, 16), '0-19', 739201, 5367),
 (datetime.date(2019, 1, 16), '20-49', 2287870, 17265),
 (datetime.date(2019, 1, 16), '50-up', 474972, 4206),
 (datetime.date(2019, 1, 17), '0-19', 717126, 5239),
 (datetime.date(2019, 1, 17), '20-49', 2226248, 17072),
 (datetime.date(2019, 1, 17), '50-up', 563612, 4194)]